apiVersion: v1
kind: Service
metadata:
  name: urotaxilbr
spec:
  type: LoadBalancer
  selector:
    app: urotaxi
    version: "1.0.1"
  ports:
    - name: lbrport
      port: 80
      targetPort: 8080