server:
  port: 8082
spring:
  application:
    name: urotaxi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://#dbhost#/urotaxidb
    username: #DB_USER_NAME#
    password: #DB_USER_PSW#
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    view:
      suffix: .html
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health